name: Develop

on:
  push:
    branches: [ develop ]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: restore node module cache
        uses: actions/cache@v1
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - run: npm ci
      - run: npm test

  build_dockerfile:
    runs-on: ubuntu-latest
    needs: build_and_test
    steps:
      - uses: actions/checkout@v2
      - name: Set up Docker Buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v1
        with:
          buildx-version: latest
          qemu-version: latest
      - name: Build and push docker image
        env:
          REPO_NAME: ${{ secrets.REPO_NAME }}
          CONTAINER_NAME: ${{ secrets.CONTAINER_NAME }}
          DOCKER_USER: ${{ secrets.DOCKER_USER }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
          docker buildx build --platform linux/amd64,linux/arm/v7 -t $REPO_NAME/$CONTAINER_NAME . --push


  update_k8s:
    runs-on: ubuntu-latest
    needs: build_dockerfile
    steps:
      - name: deploy to cluster
        uses: steebchen/kubectl@master
        env:
          KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
          CONTAINER_NAME: ${{ secrets.CONTAINER_NAME }}
        with:
          args: rollout restart --namespace=default deployment $CONTAINER_NAME --insecure-skip-tls-verify
      - name: verify deployment
        uses: steebchen/kubectl@master
        env:
          CONTAINER_NAME: ${{ secrets.CONTAINER_NAME }}
          KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
          KUBECTL_VERSION: "1.15"
        with:
          args: rollout status deployment $CONTAINER_NAME --insecure-skip-tls-verify

